version: '3'

services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - ./app:/var/www/html:cached

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html:cached
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - app

  # DB
  mysql:
    build: ./docker/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: coinlunch
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql

volumes:
  db: